# Generated by Django 3.2.24 on 2024-08-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Name', models.CharField(max_length=50)),
                ('Device_Colour', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('grey', 'grey'), ('other', 'other')], max_length=50)),
                ('Model_Number', models.CharField(max_length=14)),
                ('Manufacturer', models.CharField(choices=[('HP Inc', 'HP Inc'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('Samsung', 'Samsung'), ('Toshiba', 'Toshiba'), ('Microsoft', 'Microsoft'), ('Apple Inc', 'Apple Inc')], max_length=20)),
                ('Device_Photo', models.ImageField(default='shop/devices/device.jpg', upload_to='shop/devices')),
            ],
        ),
    ]
