# Generated by Django 3.2.24 on 2024-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Device_Colour',
            field=models.CharField(choices=[('choose a colour', 'choose a colour'), ('black', 'black'), ('white', 'white'), ('grey', 'grey'), ('other', 'other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Manufacturer',
            field=models.CharField(choices=[('choose manufacturer', 'choose manufacturer'), ('HP Inc', 'HP Inc'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('Samsung', 'Samsung'), ('Toshiba', 'Toshiba'), ('Microsoft', 'Microsoft'), ('Apple Inc', 'Apple Inc')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Model_Number',
            field=models.CharField(max_length=28),
        ),
    ]
